#### 1 

** 
- Xây dựng hàm kiểm tra số def kiem_tra_chu_so(so) để kiểm tra số truyền vào có phải là số mà tất cả các chữ số của nó đều là số chẵn hoặc đều là số lẻ. Kết quả trả về True nếu là tất cả các chữ số của số đó đều là số chẵn hoặc đều là số lẻ, ngược lại trả về False. 

- Phát sinh mảng 2 chiều có kích thước 4x4 với các phần tử có giá trị phát sinh ngẫu nhiên từ 1 đến 100 với np.random.seed(4). 

- Kiểm tra và xuất ra danh sách các phần tử trên đường chéo chính mà các chữ số của phần tử đó đều là số chẵn hoặc đều là số lẻ **



In [64]:
import numpy as np
def kiem_tra_chu_so(so): 
    str_so = str(so)
    so_chan = [ i for i in str_so if int(i)%2 == 0]
    if len(so_chan) == len(str_so): 
        return True
    else: return False 

np.random.seed(4)
arr1= np.random.randint(1,4, size= (4,4))

duong_cheo = [ arr1[i,i] for i in range(4)]
ket_qua = [int(i) for i in duong_cheo if kiem_tra_chu_so(i)]

print(f"Mảng 2 chiều 4x4: \n{arr1}")
print(f"\nDanh sách các phần tử trên đường chéo chính có chữ số đều là số chẵn hoặc số lẻ: {ket_qua}")

Mảng 2 chiều 4x4: 
[[3 3 2 2]
 [1 1 3 2]
 [3 1 2 3]
 [2 1 1 3]]

Danh sách các phần tử trên đường chéo chính có chữ số đều là số chẵn hoặc số lẻ: [2]


In [92]:
import csv
import matplotlib as plt
with open('udemy_courses.csv', 'r', encoding = 'utf-8') as file: 
    nd = csv.reader(file)
    header = next(nd)
    course_title = []
    for i in nd: 
        course_title.append(i[1])
stop_words = set([
    'a', 'an', 'the', 'and', 'in', 'on', 'of', 'at', 'for', 'with', 'as', 'to', 'by', 'is', 'are', 'it', 'that', 'this', 'which', 'be'
])
text = ' '.join(course_title)
word = text.split()
filter_words = [ i for i in word if i not in stop_words ]

cleaned_text = ' '.join(filter_words)
print(cleaned_text)

ModuleNotFoundError: No module named 'matplotlib'

In [95]:
import matplotlib.pyplot as plt


ModuleNotFoundError: No module named 'matplotlib'

In [3]:
import matplotlib.pyplot as plt 

Unexpected exception formatting exception. Falling back to standard exception


Traceback (most recent call last):
  File "/Users/trangdang/Documents/Project/data manipulation and visualization with python/.venv/lib/python3.9/site-packages/IPython/core/interactiveshell.py", line 3550, in run_code
  File "/var/folders/k7/rljyypp9343__2xr47zglj2c0000gn/T/ipykernel_59835/207665111.py", line 1, in <module>
    import matplotlib.pyplot as plt
ModuleNotFoundError: No module named 'matplotlib'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/trangdang/Documents/Project/data manipulation and visualization with python/.venv/lib/python3.9/site-packages/pygments/styles/__init__.py", line 45, in get_style_by_name
ModuleNotFoundError: No module named 'pygments.styles.default'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/trangdang/Documents/Project/data manipulation and visualization with python/.venv/lib/python3.9/site-packages/IPyth