#### 1 

** 
- Xây dựng hàm kiểm tra số def kiem_tra_chu_so(so) để kiểm tra số truyền vào có phải là số mà tất cả các chữ số của nó đều là số chẵn hoặc đều là số lẻ. Kết quả trả về True nếu là tất cả các chữ số của số đó đều là số chẵn hoặc đều là số lẻ, ngược lại trả về False. 

- Phát sinh mảng 2 chiều có kích thước 4x4 với các phần tử có giá trị phát sinh ngẫu nhiên từ 1 đến 100 với np.random.seed(4). 

- Kiểm tra và xuất ra danh sách các phần tử trên đường chéo chính mà các chữ số của phần tử đó đều là số chẵn hoặc đều là số lẻ **



In [63]:
import numpy as np
def kiem_tra_chu_so(so): 
    str_so = str(so)
    so_chan = [ i for i in str_so if int(i)%2 == 0]
    if len(so_chan) == len(str_so): 
        return True
    else: return False
print(kiem_tra_chu_so(222245))  

np.random.seed(4)
arr1= np.random.randint(1,4, size= (4,4))
print(arr1)

duong_cheo = [ arr1[i,i] for i in range(4)]
ket_qua = [int(i) for i in duong_cheo if kiem_tra_chu_so(i)]

print(f"Mảng 2 chiều 4x4: \n{arr1}")
print(f"\nDanh sách các phần tử trên đường chéo chính có chữ số đều là số chẵn hoặc số lẻ: {ket_qua}")

False
[[3 3 2 2]
 [1 1 3 2]
 [3 1 2 3]
 [2 1 1 3]]
Mảng 2 chiều 4x4: 
[[3 3 2 2]
 [1 1 3 2]
 [3 1 2 3]
 [2 1 1 3]]

Danh sách các phần tử trên đường chéo chính có chữ số đều là số chẵn hoặc số lẻ: [2]
